logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

spring:
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate.format_sql: true

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/sns
    username: chris
    password: 1234
    hikari:
      maximum-pool-size: 4

jwt:
  secret-key: newbe01_4study.sns-application-2023.secret_key
  # 30 days
  token-expired-time-ms: 2592000000
